modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues"
license = "Apache-2.0"

[[mods]]
modId = "military"
version = "${version}"
displayName = "VS2 Military"
authors = ["alex_s168", "koap", "quarsan", "Atom_14A"]
description = '''
'''
logoFile = "icon.png"

[[dependencies.vs_eureka]]
modId = "forge"
mandatory = true
versionRange = "[40.1.69,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vs_eureka]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vs_eureka]]
modId = "valkyrienskies"
mandatory = true
versionRange = "[${vs2_version},)"
ordering = "AFTER"
side = "BOTH"